sierra/config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :users
  resources :applications do
	collection do
		get :approve
		get :reject
	end
  end
  
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :games do
	collection do
		get :search
	end
end
end

sierra/app/models/application.rb
class Application < ApplicationRecord
	has_attached_file :cover_photo
	validates_attachment_content_type :cover_photo, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/

	validates :title, presence: true
	validates :description, presence: true
	validates :developers, presence: true
	validates :platforms, presence: true
	validates :url, presence: true
	validates :price, presence: true
	
end

sierra/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sierra/app/models/game.rb
class Game < ApplicationRecord
	has_attached_file :cover_photo
	validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\z/
	
	def self.search(search)
		
	end
end

sierra/app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :name, presence: true, uniqueness: true
  
end

sierra/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
	if session[:user_id]
		@current_user ||= User.find(session[:user_id])
	else
		@current_user = nil
	end
  end
end

sierra/app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
	def new
		@application = Application.new
	end
	
	def edit
		@application = Application.find(params[:id])
	end

	def create
		@application = Application.new(application_params)
		@application.status = "Waiting for Approval"
		if @application.save
			render 'submitted'
		else
			render 'new'
		end
	end

	def show
		@application = Application.find(params[:id])
	end
	
	def index
		@applications = Application.all
	end

	def update
		@application = Application.find(params[:id])
		if @application.update(application_params)
			redirect_to applications_path
		else
			render 'edit'
		end
	end

	def destroy
		@application = Application.find(params[:id])
		@application.destroy
		redirect_to applications_path
	end
	
	def approve
	    @application = Application.find(params[:id])
		hash = {}
		hash[:title] = @application.title
		hash[:description] = @application.description
		hash[:developers] = @application.developers
		hash[:platforms] = @application.platforms
		hash[:url] = @application.url
		hash[:price] = @application.price
		hash[:cover_photo] = @application.cover_photo
		@game = Game.new(hash)
		@game.save
	
		@application.status = "Approved"
		@application.save
		redirect_to applications_path
	end
	
	def reject
		@application = Application.find(params[:id])
		@application.status = "Rejected"
		@application.save
	end
	
	
	private
	def application_params
		params.require(:application).permit(:title, :description, :developers, :platforms, :url, :price, :status, :comments, :cover_photo)
	end
end

sierra/app/controllers/games_controller.rb
class GamesController < ApplicationController
	def new
		@game = Game.new
	end
	
	def search
		if params[:search].blank?
			redirect_to(root_path, alert: "No query entered!") and return
		else 
			@parameter = "%%" + params[:search].downcase + "%%"
			@results = Game.all.where("lower(title) LIKE :search OR lower(description) LIKE :search", search: @parameter)
		end
	end
	
	def edit
		@game = Game.find(params[:id])
	end

	def create
		@game = Game.new(game_params)
		@game.save
		redirect_to @game
	end

	def show
		@game = Game.find(params[:id])
	end
	
	def index
		@games = Game.all
	end

	def update
		@game = Game.find(params[:id])
		@game.update(game_params)
		redirect_to @game
	end

	def destroy
		@game = Game.find(params[:id])
		@game.destroy
		redirect_to games_path
	end
	
	private
	def game_params
		params.require(:game).permit(:title, :description, :developers, :platforms, :url, :price, :search, :cover_photo)
	end
end

sierra/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	user = User.find_by_name(params[:name])
	if user && user.authenticate(params[:password])
		session[:user_id] = user.id
		redirect_to root_url, notice: "Logged in!"
	else
		flash.now[:alert] = "Name or password invalid"
		render "new"
	end
  end

  def destroy
	session[:user_id] = nil
	redirect_to root_url, notice: "Logged out!"
  end
end

sierra/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new()
	
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
	if params[:role].blank?
		@user.role = "basic"
	end
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end
end

sierra/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

sierra/app/helpers/application_helper.rb
module ApplicationHelper
end

sierra/app/helpers/applications_helper.rb
module ApplicationsHelper
end

sierra/app/helpers/form_helper.rb
module FormHelper
end

sierra/app/helpers/games_helper.rb
module GamesHelper
end

sierra/app/helpers/sessions_helper.rb
module SessionsHelper
end

sierra/app/helpers/users_helper.rb
module UsersHelper
end

sierra/app/helpers/welcome_helper.rb
module WelcomeHelper
end

sierra/app/views/applications/_form.html.erb
<%= form_for @application do |form| %>
        <p>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
        </p>
        <p>
                <%= form.label :description %><br>
                <%= form.text_area :description %>
        </p>
        <p>
                <%= form.label :developers %><br>
                <%= form.text_field :developers %>
        </p>
        <p>
                <%= form.label :platforms %><br>
                <%= form.text_field :platforms %>
        </p>
        <p>
                <%= form.label :url %><br>
                <%= form.text_field :url %>
        </p>
        <p>
                <%= form.label :price %><br>
                <%= form.text_field :price %>
        </p>
	<p>
		<%= form.label :cover_photo %><br>
		<%= form.file_field :cover_photo %>
	</p>
        <p>
                <%= form.submit %>
        </p>
<% end %>

sierra/app/views/applications/edit.html.erb
<%= render "games/header" %>
<h3>Edit Game</h3>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

sierra/app/views/applications/index.html.erb
<%= render "games/header" %>
<% if current_user && current_user.role = "admin" %>
<head>
  <h3>Pending Applications</h3>
</head>
  <table>
	<tr>
		<th width="10%">Title</th>
		<th width="16%">Description</th>
		<th width="10%">Developers</th>
		<th width="10%">Platforms</th>
		<th width="10%">URL</th>
		<th width="10%">Price</th>
		<th width="10%">Status</th>
		<th width="10%">Comments</th>
		<th width="14%">Actions</th>
	</tr>
	<% @applications.each do |application| %>
	<% if application.status != "Approved" %>
	  <tr>
		<td><%= application.title %></td>
		<td><%= application.description %></td>
		<td><%= application.developers %></td>
		<td><%= application.platforms %></td>
		<td><%= application.url %></td>
		<td>$<%= application.price %></td>
		<td><%= application.status %></td>
		<td><%= application.comments %></td>
		<td><%= link_to 'Show', application_path(application) %></td>
		<% if application.status != "Rejected" %>
			<td><%= link_to 'Approve', approve_applications_path(:id => application.id) %></td>
			<td><%= link_to 'Reject', reject_applications_path(:id => application.id) %></td>
		<% end %>
		</tr>
	<% end %>
	<% end %>
  </table>
<% else %>
	<h3>You do not have permission to view this page</h3>
<% end %>

sierra/app/views/applications/new.html.erb
<%= render 'games/header' %>
<h2>Game Application</h2>

<%= render 'form' %>
<%= link_to 'Back', root_path %>

sierra/app/views/applications/reject.html.erb
<%= render "games/header" %>
<h3>Reject Game Application</h3>

<%= image_tag @application.cover_photo.url %>
<h2>
  <strong><%= @application.title %></strong>
</h2>
 
<p>
  <strong>Description:</strong>
  <%= @application.description %>
</p>

<p>
  <strong>Developers:</strong>
  <%= @application.developers %>
</p>
<p>
  <strong>Platforms:</strong>
  <%= @application.platforms %>
</p>

<p>
  <strong>URL:</strong>
  <%= @application.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @application.price %>
</p>

<%= form_with model: @application, local: true do |form| %>
        <p>
			<%= form.label :comments %><br>
			<%= form.text_area :comments %>
		</p>
        <p>
                <%= form.submit %>
        </p>
<% end %>

<%= link_to 'Back', applications_path %>

sierra/app/views/applications/show.html.erb
<%= render "games/header" %>

<%= image_tag @application.cover_photo.url %>
<h2>
  <strong><%= @application.title %></strong>
</h2>
 
<p>
  <strong>Description:</strong>
  <%= @application.description %>
</p>

<p>
  <strong>Developers:</strong>
  <%= @application.developers %>
</p>
<p>
  <strong>Platforms:</strong>
  <%= @application.platforms %>
</p>

<p>
  <strong>URL:</strong>
  <%= @application.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @application.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<p>
  <strong>Status Comments:</strong>
  <%= @application.comments %>
</p>

<br>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

sierra/app/views/applications/submitted.html.erb
<%= render "games/header" %>
<h3>Your application has been submitted!</h3>
<%= link_to 'Home', root_path %>

sierra/app/views/games/_form.html.erb
<%= form_with model: @game, html: {multipart: true } do |form| %>
        <p>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
        </p>
        <p>
                <%= form.label :description %><br>
                <%= form.text_area :description %>
        </p>
        <p>
                <%= form.label :developers %><br>
                <%= form.text_field :developers %>
        </p>
        <p>
                <%= form.label :platforms %><br>
                <%= form.text_field :platforms %>
        </p>
        <p>
                <%= form.label :url %><br>
                <%= form.text_field :url %>
        </p>
        <p>
                <%= form.label :price %><br>
                $<%= form.text_field :price %>
        </p>
	<p>
		<%= form.label :cover_photo %><br>
		<%= form.file_field :cover_photo %>
	</p>	
        <p>
                <%= form.submit %>
        </p>
<% end %>

sierra/app/views/games/_header.html.erb
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Challenge 01</title>
    <style>
        body {
            background-color: #5fbdff;
        }
        
        .col {
            background-color: lightgreen;
            border: 1px solid black;
        }
        
        h1 {
            display: inline-block;
            color: white;
            vertical-align: bottom;
            padding-bottom: 0;
            margin-bottom: 0;
            font-size: 500%;
        }
        
        #headerLogo {
            display: inline-block;
        }
        
        a {
            color: black;
            font-size: 150%;
        }
		
		#drop {
			display: inline;
			list-style: none;
			background-color: #DDDDDD;
			text-align: center;
			font: bold 16px Arial;
			color: #333333;
			padding: 5px 7px 5px 7px;
			border-top: 1px solid #CCCCCC;
			border-right: 1px solid #333333;
			border-bottom: 1px solid #333333;
			border-left: 1px solid #CCCCCC;
		}
		
		.dropdown {
			position: relative;
			display: inline-block
		}
		
		.dropdown-content {
			display: none;
			position: absolute;
			min-width: 160px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			padding: 12px 16px;
			z-index: 1;
		}
		
		.dropdown:hover .dropdown-content {
			display: block;
			right: 0
		}
		
    </style>
</head>
 <header>
        <div class="row">
            <div class="col-6 justify-content-end align-items-center">
                <%= link_to image_tag('logo.jpg', :height => "65%", :width => "20%"), url_for({:controller => 'games', :action => 'index'}),  :class => 'quick' %>
                <h1 id="title">Sierra Store</h1>
            </div>


            <div class="col-5 d-flex justify-content-end align-items-center" float:"right" style="margin-left: auto">
                <%= form_tag(search_games_path, method: :get, class: "search-form") do %>
					<%= text_field_tag(:search, params[:search]) %>
					<%= submit_tag ("Search") %>
					<% end %>
                <% if current_user %>
					<div class = "dropdown">
						<span id="drop"><%= current_user.name%></span>
						<ul class="dropdown-content">
							<%= button_to "Log Out", { :controller => "sessions", :action => "destroy" }, :method => :get %>
							<%= button_to "Submit a game", { :controller => "applications", :action => "new" }, :method => :get %>
							<% if current_user.role == "admin" %>
								<%= button_to "Manage Applications", { :controller => "applications", :action => "index" }, :method => :get %>
								<%= button_to "Manage Users", { :controller => "users", :action => "index" }, :method => :get %>
							<% end %>
						</ul>
					</div>
				<% else %>
					<%= button_to "Log In/Sign Up", { :controller => "sessions", :action => "new" }, :method => :get %>
				<% end %>
            </div>
        </div>
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js " integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1 " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js " integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM " crossorigin="anonymous "></script>
</header>

sierra/app/views/games/edit.html.erb
<%= render "games/header" %>
<h3>Edit Game</h3>

<%= render 'form' %>


<%= link_to 'Delete Game', [ @game ],
	method: :delete,
	data: { confirm: 'Are you sure?' } %> 
<%= link_to 'Back', games_path %>

sierra/app/views/games/index.html.erb
<%= render "games/header" %>
<br>
<h3>All Games</h3>

<br>
<table border="1" id="games" style="text-align: center">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Description</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
<% @games.each do |game| %>
	<tr>
		<td width="350" height="200"><%= image_tag game.cover_photo.url, size: "350x200", :alt => "rss feed" %></td>
		<td width="200" height="200"><h5 class="card-title"><%= game.title %></h5></td>
		<td width="300" height="200"><div style="position:relative">			
			<p class="card-text"><%= game.description %></p>
			<div class="btn-group " style="bottom:0">
				<%= link_to 'View', game_path(game) %> |
				<%= link_to 'Buy', "#{game.url}", :target => "_blank" %>
			</div>
		</div></td>
		<td width="70" height="200">$<%= game.price %></td>
			
	<% end %>
	</tbody>
</table>


<script src="https://code.jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src=" https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"></script>
<script>
	$(document).ready(function() {
		$('#games').DataTable();
        });
</script>


 

sierra/app/views/games/new.html.erb
<h1>Create a New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

sierra/app/views/games/search.html.erb
<%= render 'games/header' %>
<h2>Search Results:</h2>
<table border="1" style="width:100%, text-align:center">
<thead>
	<tr>
		<th></th>
    		<th>Title</th>
    		<th>Description</th>
		<th>Price</th>
		<th></th>
 	 </tr>
</thead>
  <% @results.each do |result| %>
	  <tr>
		  <td width="350" height="200"><%= image_tag result.cover_photo.url, size: "350x200", :alt => "rss feed" %></td>
      <td width="200"><%= result.title %></td>
      <td><%= result.description %></td>
      <td width="70"><%= result.price %></td>
      <td width="200"><%= link_to 'View', game_path(result) %> | <%= link_to 'Buy', "#{result.url}", :target => "_blank" %> </td>
    </tr>
  <% end %>
</table>

sierra/app/views/games/show.html.erb
<%= render "games/header" %>


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Game</title>
    <style>
        body {
            background-color: #5fbdff;
        }
        
        .col {
            background-color: lightgreen;
            border: 1px solid black;
        }
        
        h1 {
            display: inline-block;
            color: white;
            vertical-align: bottom;
            padding-bottom: 0;
            margin-bottom: 0;
            font-size: 500%;
        }
        
        #headerLogo {
            display: inline-block;
        }
        
        .nav-link {
            color: black;
            font-size: 150%;
        }
    </style>
</head>

<body>


    <div class="row">
        
        <div class="container">

            <!-- Portfolio Item Heading -->
            <h1 class="my-4"><%= @game.title %></h1>

            <!-- Portfolio Item Row -->
            <div class="row">

                <div class="col-md-8">
                    <%= image_tag @game.cover_photo.url, size: "700x500" %>
                </div>

                <div class="col-md-4">
                    <h3 class="my-3"><strong>Description</strong></h3>
                    <p><%= @game.description %></p>
                    <h3 class="my-3"><strong>Game Details</strong></h3>
                    <h5>Platforms</h5><br>
			<p><%= @game.platforms %></p>
                    <h5>Developers</h5>
			<p><%= @game.developers %></p>
                    
                    <h3 class="my-3">Price</h3>
			<p><%= @game.price %></p>
                    <% if current_user && current_user.role = "admin" %>
			<%= link_to 'Edit', edit_game_path(@game) %>
			<% end %>
                </div>

            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->
    </div>



    </section>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js " integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1 " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js " integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM " crossorigin="anonymous "></script>
</body>

sierra/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sierra</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sierra/app/views/layouts/search.html.erb
<%= render 'games/header' %>
<h2>Search Results:</h2>
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Description</th>
	<th>Developers</th>
    <th>Platforms</th>
	<th>Link</th>
    <th>Price</th>
    <th></th>
  </tr>
  
  <% @results.each do |result| %>
    <tr>
      <td><%= result.title %></td>
      <td><%= result.description %></td>
	  <td><%= result.developers %></td>
      <td><%= result.platforms %></td>
	  <td><%= result.url %></td>
      <td><%= result.price %></td>
      <td><%= link_to 'View', game_path(result) %></td>
    </tr>
  <% end %>
</table>

sierra/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Sign Up!" %>
  </div>
<% end %>

sierra/app/views/users/edit.html.erb
<h1>Editing User</h1>

<% if current_user && current_user.role = "admin" %>
	<%= form_with(model: @user, local: true) do |form| %>
		<% if @user.errors.any? %>
			<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  
    <div class="field">
	  <%= form.label :role %>
	  <%= form.text_field :role, id: :user_role %>
    </div>
  
  <div class="actions">
    <%= form.submit "Done" %>
  </div>
<% end %>

<%= link_to 'Quit without saving', root_path %> |
<%= link_to 'Delete', user_path(@user),
	      method: :delete,
	      data: { confirm: 'Are you sure?' } %>
<% else %>
	<h3>You cannot edit users</h3>
<% end %>

sierra/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user && current_user.role = "admin" %>
	<%= render "games/header" %>
	<h3>Manage Users</h3>

	<table>
		<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Role</th>
			<th colspan="3"></th>
		</tr>
		</thead>

		<tbody>
		<% @users.each do |user| %>
			<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= user.role %></td>
			<td><%= link_to 'Edit', edit_user_path(user) %></td>
			<td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
		</tbody>
	</table>

<br>

<%= link_to 'New User', new_user_path %><br>
<%= link_to 'Home', root_path %>
<% end %>

sierra/app/views/users/new.html.erb
<h1>New User Sign Up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

sierra/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
	<strong>Role:</strong>
	<%= @user.role %>
</p>

<%= link_to 'Back', users_path %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Home', root_path %>